events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    upstream apim5 {
        server fastapi_m5:8000;
    }

    server {
        listen 80;
        server_name localhost;
        client_max_body_size 50m;

         # Aumentar timeouts para entrenamientos largos
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;

        location /apim5/ {
            proxy_pass http://apim5/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /apim5; 

            proxy_read_timeout 600s;  # 10 minutos para entrenamiento
        }

        # Configuración específica para el endpoint de entrenamiento
        location /apim5/train {
            proxy_pass http://fastapi_m5:8000/train;
            proxy_read_timeout 600s;
            proxy_connect_timeout 600s;
        }

        location / {
            root /usr/share/nginx/html/dist;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location = /favicon.ico {
            access_log off;
            log_not_found off;
            return 204;
        }
    }
}