-- Crear usuario postgres si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN
      CREATE ROLE postgres WITH LOGIN PASSWORD 'Qazwsx12' SUPERUSER;
   END IF;
END
$$;

-- Crear usuario taskpredictoruser si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'taskpredictoruser') THEN
      CREATE ROLE "taskpredictoruser" WITH LOGIN PASSWORD 'Qazwsx12';
   END IF;
END
$$;

-- Crear base de datos y asignar propietario
SELECT 'CREATE DATABASE "dbPredicterManager" OWNER "taskpredictoruser"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dbPredicterManager')\gexec

GRANT ALL PRIVILEGES ON DATABASE "dbPredicterManager" TO "taskpredictoruser";
GRANT CONNECT ON DATABASE "dbPredicterManager" TO "taskpredictoruser";

\connect dbPredicterManager

-- Una vez conectados a la base de datos, asignamos permisos al usuario taskpredictoruser para el esquema public y las tablas que se creen en el futuro
GRANT USAGE ON SCHEMA public TO "taskpredictoruser";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "taskpredictoruser";


-- Coloca las tabla de tasks manager en el esquema public y asigna permisos
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "taskpredictoruser";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "taskpredictoruser";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO "taskpredictoruser";   

CREATE Table IF Not Exists tasks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) COLLATE pg_catalog."default" NOT NULL,
    contenido TEXT COLLATE pg_catalog."default",
    completada BOOLEAN DEFAULT FALSE,
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tasks
    OWNER to "taskpredictoruser";



