-- Crear usuario postgres si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN
      CREATE ROLE postgres WITH LOGIN PASSWORD 'Qazwsx12' SUPERUSER;
   END IF;
END
$$;

-- Crear usuario taskpredictoruser si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'taskpredictoruser') THEN
      CREATE ROLE "taskpredictoruser" WITH LOGIN PASSWORD 'Qazwsx12';
   END IF;
END
$$;

-- Crear base de datos y asignar propietario
SELECT 'CREATE DATABASE "dbPredicterManager" OWNER "taskpredictoruser"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dbPredicterManager')\gexec

GRANT ALL PRIVILEGES ON DATABASE "dbPredicterManager" TO "taskpredictoruser";
GRANT CONNECT ON DATABASE "dbPredicterManager" TO "taskpredictoruser";

\connect dbPredicterManager

-- Una vez conectados a la base de datos, asignamos permisos al usuario taskpredictoruser para el esquema public y las tablas que se creen en el futuro
GRANT USAGE ON SCHEMA public TO "taskpredictoruser";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "taskpredictoruser";


-- Coloca las tabla de tasks manager en el esquema public y asigna permisos
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "taskpredictoruser";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "taskpredictoruser";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "taskpredictoruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO "taskpredictoruser";   

DO
$$
BEGIN
    CREATE TABLE IF NOT EXISTS public.users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR(255) NOT NULL,
        apellido VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        descripcion VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        status INTEGER DEFAULT 0,
        startline TIMESTAMPTZ,
        deadline TIMESTAMPTZ,        
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS public.datasets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_filename VARCHAR(255) NOT NULL,
        storage_key VARCHAR(255) UNIQUE NOT NULL,
        storage_root TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS public.dataset_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dataset_id BIGINT NOT NULL REFERENCES public.datasets(id) ON DELETE CASCADE,
        version_number INTEGER NOT NULL,
        parent_version_id BIGINT REFERENCES public.dataset_versions(id) ON DELETE SET NULL,
        storage_path TEXT NOT NULL,
        row_count INTEGER NOT NULL DEFAULT 0,
        column_count INTEGER NOT NULL DEFAULT 0,
        columns_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (dataset_id, version_number)
    );

    CREATE TABLE IF NOT EXISTS public.dataset_operations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dataset_id BIGINT NOT NULL REFERENCES public.datasets(id) ON DELETE CASCADE,
        dataset_version_id BIGINT NOT NULL REFERENCES public.dataset_versions(id) ON DELETE CASCADE,
        operation_name VARCHAR(100) NOT NULL,
        parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS public.tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_padre BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE,
        titulo VARCHAR(255) NOT NULL,
        id_user BIGINT REFERENCES public.users(id) ON UPDATE CASCADE,
        contenido TEXT,
        completada BOOLEAN DEFAULT FALSE,
        startline TIMESTAMPTZ,
        deadline TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_dataset_versions_dataset_id_version_number
        ON public.dataset_versions (dataset_id, version_number DESC);

    CREATE INDEX IF NOT EXISTS idx_dataset_operations_dataset_id_created_at
        ON public.dataset_operations (dataset_id, created_at DESC);

END
$$;    